# Generated by Django 4.2 on 2023-05-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_created',
        ),
    ]
