# Generated by Django 4.2 on 2023-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_remove_attendance_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_percentage',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=5),
            preserve_default=False,
        ),
    ]
